version: '3'
volumes:
    dados:
services:
    frontend:
        image: nginx:1.13
        volumes:
            - ./web:/usr/share/nginx/html/
        ports:
            - 80:80
    db:
        image: postgres:9.6
        environment: 
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - dados:/var/lib/postgresql/data
            - ./scripts:/scripts
            - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql